using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using static System.Runtime.InteropServices.JavaScript.JSType;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.TrackBar;

namespace CaiSiGpxGenerator
{
    /*
     * TODO: check download!
     *  create files: separate into si.html and .js files
     * 
     * 
     * 
     * URLs:
     *  get all regions:
     *  https://sentieroitalia.cai.it/de/der-weg/etappenblaetter/
     *  
     *  stages of one specific region: These region-specific URLs are NOT used in any code
     *  Abruzzo:        https://sentieroitalia.cai.it/de/der-weg/etappenblaetter/?region=abruzzo
     *  Emilia-Romagna: https://sentieroitalia.cai.it/de/der-weg/etappenblaetter/?region=emilia-romagna
     *  Friuli-Venezia Giulia:  https://sentieroitalia.cai.it/de/der-weg/etappenblaetter/?region=friuli-venezia-giulia
     *  Trentino-Alti Adige:    https://sentieroitalia.cai.it/de/der-weg/etappenblaetter/?region=trentino-alto-adige
     *  Valle d'Aosta:          https://sentieroitalia.cai.it/de/der-weg/etappenblaetter/?region=valle-d-aosta
     *  
     *  To get all stages of one region: This returns .json data and in the array 'hits' we get the stage ids 
     *  such as SI-N01 in field 'name'
     *  Regions with more than one word must have spaces between the word. upper or lower case is not relevant
     *  Replace '-' by a space %20 and ' by %27
     *  https://osm2cai.cai.it/api/v2/elasticsearch?app=osm2cai_app_2&layer=6&query=Abruzzo or abruzzo
     *  https://osm2cai.cai.it/api/v2/elasticsearch?app=osm2cai_app_2&layer=6&query=emilia%20romagna
     *  https://osm2cai.cai.it/api/v2/elasticsearch?app=osm2cai_app_2&layer=6&query=friuli%20venezia%20giulia
     *  https://osm2cai.cai.it/api/v2/elasticsearch?app=osm2cai_app_2&layer=6&query=trentino%20alto%20adige
     *  https://osm2cai.cai.it/api/v2/elasticsearch?app=osm2cai_app_2&layer=6&query=Valle%20d%27Aosta
     *  
     *  To get the GPX data for each track:
     *  https://sentieroitalia.cai.it/de/track/si-n01: this returns the web page for that one stage, and this web page contains
     *  the GPX data in json format at key 'data-track-feature'. To convert that json data into a .gpx file we do this:
     *  - generate the data into a javascript .js file. This file contains one variable with that json data.
     *  - generate an .html file that includes the .js file and uses function togpx()
     *          from file togpx-0.5.4.js to create and 'download' the .gpx file. 
     *          
     *          
     *          File togpx-0.5.4.js is from here on 26.9.2026
     *          https://cdn.jsdelivr.net/npm/togpx@0.5.4/togpx.min.js
     *          This opens javascript in the browser -> Save as togpx-0.5.4.js

     */
    public class CaiSiGpxGenerator
    {
        public const string HtmlFileName = "si.html";

        public static string TextToSlug(string text)
        {
            string slug = text.ToLowerInvariant();

            slug = slug
                .Replace("à", "a")
                .Replace("è", "e")
                .Replace("é", "e")
                .Replace("ì", "i")
                .Replace("ò", "o")
                .Replace("ù", "u");

            slug = slug.Replace("'", "-");

            slug = Regex.Replace(slug, @"[^a-z0-9]+", "-");

            slug = slug.Trim('-');

            return slug;
        }

        // return a valid var name in javascript
        public static string TextToVarname(string text)
        {
            string slug = text.ToLowerInvariant();

            slug = slug
                .Replace("à", "a")
                .Replace("è", "e")
                .Replace("é", "e")
                .Replace("ì", "i")
                .Replace("ò", "o")
                .Replace("ù", "u");

            slug = slug.Replace("'", "");

            slug = Regex.Replace(slug, @"[^a-z0-9]+", "_");

            return slug;
        }


        public static async Task CreateHtmlFiles(MainForm form, string folder,
            Dictionary<string, RegionInfo> dictRegions)
        {
            StreamWriter writer;

            // c:\temp\si.html
            string fileNameHtml = Path.Combine(folder, HtmlFileName);
            string text;

            writer = new StreamWriter(fileNameHtml);

            writer.WriteLine($"<!-- Generated by Christoph Maurer ch.maurer@gmx.de on {DateTime.Now:dd.MM.yyyy} -->");

            // <script src="../togpx-0.5.4.js"></script>
            writer.WriteLine("<script src=\"togpx-0.5.4.js\"></script>");
            foreach (string region in dictRegions.Keys)
            {
                if (form._abort)
                {
                    break;
                }
                List<TrackInfo> trackInfos = dictRegions[region].trackInfos;
                foreach (TrackInfo trackInfo in trackInfos)
                {
                    if (form._abort)
                    {
                        break;
                    }

                    string track = trackInfo.trackId;
                    text = $"<script src=\"{region}/{region}_{track}.js\"></script>";

                    // <script src="abruzzo/abruzzo_sin01.js"></script>
                    writer.WriteLine(text);
                }
            }

            writer.WriteLine("<script>");

            writer.WriteLine(@"
const WaitTimeMilliseconds = 1000;
function sleep(ms)
{
    return new Promise(resolve => setTimeout(resolve, ms));
}");

            foreach (string region in dictRegions.Keys)
            {
                if (form._abort)
                {
                    break;
                }

                List<TrackInfo> trackInfos = dictRegions[region].trackInfos;
                foreach (TrackInfo trackInfo in trackInfos)
                {
                    if (form._abort)
                    {
                        break;
                    }

                    string track = trackInfo.trackId;

                    writer.WriteLine($"// {region} {track}");

                    text = $$"""
const trackFeature_{{region}}_{{track}} = JSON.parse(trackFeatureJson_{{region}}_{{track}});
const gpxString_{{region}}_{{track}} = togpx(trackFeature_{{region}}_{{track}});
const blob_{{region}}_{{track}} = new Blob([gpxString_{{region}}_{{track}}], { type: "application/gpx+xml" });
const a_{{region}}_{{track}} = document.createElement("a");
function downloadGpx_{{region}}_{{track}}()
{
    url_{{region}}_{{track}} = URL.createObjectURL(blob_{{region}}_{{track}});
    a_{{region}}_{{track}}.href = url_{{region}}_{{track}};
    a_{{region}}_{{track}}.download = "{{region}}_{{track}}.gpx";
    a_{{region}}_{{track}}.click();
    URL.revokeObjectURL(url_{{region}}_{{track}});
}
""";
                    writer.WriteLine(text);
                }

                writer.WriteLine($"async function downloadGpx_{region}()");
                writer.WriteLine("{");
                foreach (TrackInfo trackInfo in trackInfos)
                {
                    if (form._abort)
                    {
                        break;
                    }

                    string track = trackInfo.trackId;
                    writer.WriteLine($"    downloadGpx_{region}_{track}();");
                    writer.WriteLine($"    await sleep(WaitTimeMilliseconds);");
                }
                writer.WriteLine("}");
            }

            writer.WriteLine($"async function downloadGpx()");
            writer.WriteLine("{");
            foreach (string region in dictRegions.Keys)
            {
                if (form._abort)
                {
                    break;
                }
                writer.WriteLine($"    await downloadGpx_{region}();");
            }
            writer.WriteLine("}");

            writer.WriteLine("</script>");

            int noTotal = dictRegions.Values.Sum(list => list.trackInfos.Count);

            writer.WriteLine("<html>");
            writer.WriteLine("<h2>Sentiero Italia</h2>");
            writer.WriteLine("<button onclick=\"downloadGpx()\">Download all</button> " + noTotal.ToString() + " tracks");

            foreach (string region in dictRegions.Keys)
            {
                if (form._abort)
                {
                    break;
                }

                writer.WriteLine("");
                writer.WriteLine($"<h2>{region}</h2>");
                writer.WriteLine($"<button onclick=\"downloadGpx_{region}()\">Download all {region}</button> "
                    + dictRegions[region].trackInfos.Count.ToString() + " tracks");
                writer.WriteLine($"</br>");

                List<TrackInfo> trackInfos = dictRegions[region].trackInfos;
                foreach (TrackInfo trackInfo in trackInfos)
                {
                    if (form._abort)
                    {
                        break;
                    }

                    string track = trackInfo.trackId;
                    writer.WriteLine($"<button onclick=\"downloadGpx_{region}_{track}()\">Download {region} {track}</button>");
                }
            }
            writer.WriteLine("</html>");
            writer.Close();
            writer = null;

            form.WriteProgress($"Ready");
        }


        public static async Task CreateJsFiles(MainForm form, string folder,
            Dictionary<string, RegionInfo> dictRegions)
        {


            //
            // create .js files with GPS data
            //
            int noTotal = dictRegions.Values.Sum(list => list.trackInfos.Count);
            int cntTotal = 0;
            foreach (string region in dictRegions.Keys)
            {
                if (form._abort)
                {
                    break;
                }

                List<TrackInfo> trackInfos = dictRegions[region].trackInfos;
                int noTracks = trackInfos.Count;
                int cntTrack = 0;
                foreach (TrackInfo trackInfo in trackInfos)
                {
                    cntTotal++;
                    cntTrack++;

                    if (form._abort)
                    {
                        break;
                    }

                    string track = trackInfo.trackId;
                    string url = trackInfo.trackUrl;

                    // c:\temp\abruzzo
                    string outputFolder = Path.Combine(folder, region);

                    // c:\temp\abruzzo\abruzzo_sin01.js
                    string outputFileJs = Path.Combine(outputFolder, region + "_" + track + ".js");

                    // c:\temp\abruzzo\abruzzo_sin01.html
                    string outputFileHtml = Path.Combine(outputFolder, region + "_" + track + ".html");

                    string strCountTotal = $"{cntTotal}/{noTotal}";
                    string strCountRegion = $"{cntTrack}/{noTracks}";
                    form.WriteProgress("Downloading: [" + region + " " + strCountRegion + "] - " + strCountTotal + " - " + url);

                    using HttpClient client = new HttpClient();

                    // CAI-Seite herunterladen
                    string html = await client.GetStringAsync(url);

                    form.WriteProgress($"Loaded HTML: {html.Length:N0} chars");

                    // data-track-feature suchen: ends with =' or ="
                    string marker = "data-track-feature=";

                    int start = html.IndexOf(marker);

                    if (start < 0)
                    {
                        form.WriteProgress("ERROR: data-track-feature not found: " + url);
                        continue;
                    }

                    char quoteChar = html[start + marker.Length];

                    start += marker.Length + 1;

                    int end = html.IndexOf(quoteChar, start);

                    if (end < 0)
                    {
                        form.WriteProgress("ERROR: End of data-track-feature not found: " + url);
                        continue;
                    }

                    string encodedTrack = html.Substring(start, end - start);

                    // HTML-Entities zurückwandeln
                    string trackFeatureJson = WebUtility.HtmlDecode(encodedTrack);

                    form.WriteProgress($"data-track-feature: {trackFeatureJson.Length:N0} Zeichen");

                    // Kontrolle
                    if (!trackFeatureJson.StartsWith("{"))
                    {
                        form.WriteProgress("ERROR: The extracted data does not start with '{': " + url);
                        continue;
                    }

                    // JavaScript-Datei erzeugen
                    // const trackFeatureJson_abruzzo_sin01 = "...
                    string js =
                        "const trackFeatureJson_" + region + "_" + track + " = " +
                        JsonString(trackFeatureJson) +
                        ";\n";

                    Directory.CreateDirectory(outputFolder);

                    File.WriteAllText(
                        outputFileJs,
                        js,
                        new UTF8Encoding(false));

                    form.WriteProgress($"Generated file {outputFileJs}");
                }
            }
            form.WriteProgress($"Ready");
        }


        // Erzeugt einen sicheren JavaScript-String
        static string JsonString(string value)
        {
            var sb = new StringBuilder();

            sb.Append('"');

            foreach (char c in value)
            {
                switch (c)
                {
                    case '\\':
                        sb.Append("\\\\");
                        break;

                    case '"':
                        sb.Append("\\\"");
                        break;

                    case '\r':
                        sb.Append("\\r");
                        break;

                    case '\n':
                        sb.Append("\\n");
                        break;

                    case '\t':
                        sb.Append("\\t");
                        break;

                    default:
                        sb.Append(c);
                        break;
                }
            }

            sb.Append('"');

            return sb.ToString();
        }

        /// <summary>
        /// get all regions: the base url
        /// https://sentieroitalia.cai.it/de/der-weg/etappenblaetter/
        /// returns a select that contains all the regions, they are parsed out of the select filter_italian_region of the html page.
        /// </summary>
        /// <param name="form"></param>
        /// <param name="url"></param>
        /// <param name="dictRegions"></param>
        /// <returns></returns>

        public static async Task ExtractRegions(MainForm form, string url, 
            Dictionary<string, RegionInfo> dictRegions)
        {
            string baseUrl = url;

            using HttpClient client = new HttpClient();

            // Hauptseite herunterladen
            form.WriteProgress("Downloading " + baseUrl);
            string html = await client.GetStringAsync(baseUrl);

            // EXAKT das Regions-Select suchen
            Match selectMatch = Regex.Match(
                html,
                @"<select\s+id=""filter_italian_region""[^>]*>(.*?)</select>",
                RegexOptions.IgnoreCase |
                RegexOptions.Singleline);

            if (!selectMatch.Success)
            {
                form.WriteProgress("ERROR: Regions-Select not found");
                return;
            }

            // Nur den Inhalt dieses Selects
            string selectHtml = selectMatch.Groups[1].Value;

            // Nur die Options dieses Selects
            MatchCollection options = Regex.Matches(
                selectHtml,
                @"<option\s+value=""([^""]+)""[^>]*>",
                RegexOptions.IgnoreCase);

            int count = 0;

            form.WriteProgress("Processing Regions-Select");

            foreach (Match option in options)
            {
                string region = WebUtility.HtmlDecode(option.Groups[1].Value);

                // Leere Option "Region auswählen" überspringen
                if (string.IsNullOrWhiteSpace(region))
                    continue;

                count++;

                // URL der Region erzeugen
                string regionSlug = TextToSlug(region);

                string regionUrl = baseUrl + "?region=" + regionSlug;
                string regionApiUrl = region.Replace("-", " ");

                // abruzzo, emilio%20romana, valle%20d%27aosta
                regionApiUrl = Uri.EscapeDataString(regionApiUrl.ToLowerInvariant());
                string apiUrl = "https://osm2cai.cai.it/api/v2/elasticsearch?app=osm2cai_app_2&layer=6&query="
                    + regionApiUrl;

                RegionInfo regionInfo = new RegionInfo();
                regionInfo.region = TextToVarname(region);
                regionInfo.regionUI = region;
                regionInfo.regionUrl = regionUrl;
                regionInfo.apiUrl = apiUrl;
                dictRegions.Add(regionInfo.region, regionInfo);
            }

            form.WriteProgress("Ready");
        }

        public static async Task GetRegionStageUrls(MainForm form, string region,
            Dictionary<string, RegionInfo> dictRegions)
        {
            RegionInfo regionInfo = dictRegions[region];

            regionInfo.trackInfos.Clear();

            using HttpClient client = new HttpClient();

            string apiUrl = regionInfo.apiUrl;

            form.WriteProgress("Downloading " + apiUrl);

            string json = await client.GetStringAsync(apiUrl);

            using JsonDocument doc = JsonDocument.Parse(json);

            form.WriteProgress("Processing tracks");

            foreach (JsonElement hit in doc.RootElement
                .GetProperty("hits")
                .EnumerateArray())
            {
                if (!hit.TryGetProperty("name", out JsonElement nameElement))
                    continue;

                string name = nameElement.GetString() ?? "";

                if (string.IsNullOrWhiteSpace(name))
                    continue;

                string slug = TextToSlug(name);

                string trackUrl = "https://sentieroitalia.cai.it/de/track/" + slug + "/";

                TrackInfo trackInfo = new TrackInfo();
                trackInfo.trackId = TextToVarname(name);
                trackInfo.trackIdUi = name;
                trackInfo.trackUrl = trackUrl;
                regionInfo.trackInfos.Add(trackInfo);
            }
            form.WriteProgress("Ready");
        }

        public static void MoveFiles(MainForm form, string src, string dst)
        {
            // src contains:
            // abruzzo_si_p01.gpx, emilia_romagna_si_g01.gpx
            // the first part before the "_si_" is used as the subfolder name 
            //
            //
            // dst contains:
            //      togpx-0.5.4.js
            //      si.html
            //      abruzzo\abruzzo_si_n01.js
            //      abruzzo\abruzzo_si_p01.js
            // ...  emilia_romagna\emilia_romagna_si_g01.gpx
            //      friuli_venezia_giulia\friuli_venezia_giulia_si_a07.gpx
            //      trentino_alto_adige\trentino_alto_adige_si_c02.gpx
            //
            FileInfo[] files = new DirectoryInfo(src).GetFiles("*.gpx");
            int count = 0;
            foreach (FileInfo fileInfo in files)
            {
                count++;

                // 0          1  2
                // abruzzo_si_n01.gpx
                //
                string[] arFileName = fileInfo.Name.Split("_si_");
                if (arFileName.Length <=0)
                {
                    continue;
                }
                string targetFolder = Path.Combine(dst, arFileName[0]);
                string dstFileName = Path.Combine(targetFolder , fileInfo.Name);
                // c:\temp\abruzzo
                if (!Directory.Exists(targetFolder))
                {
                    Directory.CreateDirectory(targetFolder);
                }

                // C:\Users\chmau\Downloads\abruzzo_si_n01.gpx -> c:\temp\abruzzo\.
                form.WriteProgress("moving file: " + count.ToString() + "/" + files.Length.ToString()
                    + fileInfo.Name + " ->" + dstFileName);
                File.Move(fileInfo.FullName, dstFileName);
            }
            form.WriteProgress("Ready");
        }
    }
}

